In [1]:
import numpy
import pandas
import six
import tensorflow as tf

import CS230

# load data sets

In [2]:
file_paths = CS230.data.get_all_file_paths()
file_path = file_paths[0]

train_percent = 0.9
dev_percent = 0.05
test_percent = 0.05

df = CS230.data.load(file_path)
df = CS230.data.stride_rows(df, stride=10)
df = CS230.data.add_derivatives(df, stride=1)
df = CS230.data.clean_discontinuities(df, stride=1)

df_train, df_dev, df_test = CS230.data.get_data_sets(df, train_percent, dev_percent, test_percent, 
                                                     CS230.data.COLUMNS_HUMAN_INPUT, CS230.data.COLUMNS_DERIV)

# define model

In [3]:
model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(len(CS230.data.COLUMNS_DERIV), activation='relu'))

#model.add(tf.keras.layers.Dropout(0.2))

model.add(tf.keras.layers.Dense(len(CS230.data.COLUMNS_DERIV), activation='sigmoid'))

In [4]:
model.compile(optimizer=tf.train.AdamOptimizer(0.001), loss='categorical_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:From /home/dave/venv/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

# view training data set

In [5]:
df_train.head()

,brake,throttle,handwheelAngle,deriv_axCG,deriv_ayCG,deriv_pitchAngle,deriv_pitchRate,deriv_rollAngle,deriv_rollRate,deriv_vxCG,deriv_vyCG,deriv_wheelAccelFL,deriv_wheelAccelFR,deriv_wheelAccelRL,deriv_wheelAccelRR,deriv_yawAngle,deriv_yawRate
0,0.5,0.8,1.5,-1.06,0.08,-0.04,-2.32,0.05,3.99,-0.02,0.00,-5.30,-2.74,2.75,-8.95,-0.02,0.17
1,0.0,0.7,-33.0,0.00,0.06,0.00,-0.05,0.00,0.03,0.00,0.00,0.19,0.10,-0.29,-0.01,-0.01,0.22
2,0.0,6.3,0.8,0.08,-1.85,-0.01,1.66,0.04,0.75,0.02,-0.01,-2.74,5.10,-5.79,-8.69,-0.02,-0.26
3,0.0,0.7,-11.2,0.32,-0.59,-0.05,-11.88,0.03,10.49,-0.06,-0.01,-19.03,11.58,-2.45,-5.40,-0.08,-0.46
4,0.0,3.3,1.3,0.08,-1.13,0.02,0.64,0.00,-2.46,0.01,0.00,1.28,-0.79,-1.47,-1.80,0.00,0.00

In [6]:
x_train = tf.cast(df_train[CS230.data.COLUMNS_HUMAN_INPUT].values, tf.float32)
y_train = tf.cast(df_train[CS230.data.COLUMNS_DERIV].values, tf.float32)

In [7]:
df_train[CS230.data.COLUMNS_HUMAN_INPUT].values

array([[  0.5,   0.8,   1.5],
       [  0. ,   0.7, -33. ],
       [  0. ,   6.3,   0.8],
       ...,
       [  0. ,   1. , 250.4],
       [  0. ,   2.5,   6.6],
       [ 12.6,   2.2, -34.2]])

In [8]:
df_train[CS230.data.COLUMNS_DERIV].values

array([[-1.06,  0.08, -0.04, ..., -8.95, -0.02,  0.17],
       [ 0.  ,  0.06,  0.  , ..., -0.01, -0.01,  0.22],
       [ 0.08, -1.85, -0.01, ..., -8.69, -0.02, -0.26],
       ...,
       [-0.24, -0.68,  0.03, ..., -4.79,  0.42, -0.04],
       [-0.25, -0.02,  0.03, ...,  0.95,  0.02,  0.71],
       [ 0.19, -0.2 ,  0.02, ..., -0.3 ,  0.  , -0.09]])

# train model

In [9]:
model.fit(x_train, y_train, epochs=10, steps_per_epoch=50)

WARNING:tensorflow:From /home/dave/venv/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
50/50 [==============================] - 3s 50ms/step - loss: 0.0226 - acc: 0.0565
Epoch 2/10
50/50 [==============================] - 2s 42ms/step - loss: -0.2446 - acc: 0.0018
Epoch 3/10
50/50 [==============================] - 2s 45ms/step - loss: -0.4418 - acc: 0.0019
Epoch 4/10
50/50 [==============================] - 2s 43ms/step - loss: -0.6012 - acc: 0.0216
Epoch 5/10
50/50 [==============================] - 2s 44ms/step - loss: -0.7659 - acc: 0.0138
Epoch 6/10
50/50 [==============================] - 2s 42ms/step - loss: -0.9053 - acc: 0.0056
Epoch 7/10
50/50 [==============================] - 2s 42ms/step - loss: -1.0076 - acc: 0.0510
Epoch 8/10
50/50 [==============================] - 2s 43ms/step - loss: -1.1060 - acc: 0.0646
Epoch 9/10
50/50 [==============================] - 2s 44ms/step - loss: -1.1835 - acc: 0.0667
Epoch 10/10
50/50 [==============================] - 2s 43ms/step - loss: -1.2454 - acc: 0.0679

# view dev set

In [10]:
df_dev.head()

,brake,throttle,handwheelAngle,deriv_axCG,deriv_ayCG,deriv_pitchAngle,deriv_pitchRate,deriv_rollAngle,deriv_rollRate,deriv_vxCG,deriv_vyCG,deriv_wheelAccelFL,deriv_wheelAccelFR,deriv_wheelAccelRL,deriv_wheelAccelRR,deriv_yawAngle,deriv_yawRate
0,13.5,0.7,-32.9,0.07,0.01,0.00,0.04,0.00,-0.03,0.00,0.00,0.00,0.30,-0.30,0.07,0.01,-0.52
1,0.0,10.4,-35.6,-1.10,2.16,-0.03,-0.92,-0.02,1.58,0.03,0.03,-3.14,-3.33,3.92,-1.11,-0.21,0.43
2,0.0,0.8,-33.1,-0.07,0.01,0.00,-0.23,0.00,-0.19,-0.01,0.00,0.09,-0.30,-0.30,0.43,0.00,-0.20
3,0.0,21.2,-12.0,-3.43,-1.84,0.04,4.07,0.00,-0.84,-0.01,-0.01,-2.65,-8.44,-3.93,-24.44,-0.08,-0.11
4,0.0,6.0,-0.7,-0.35,-5.85,0.09,5.84,-0.10,-14.92,0.00,-0.01,4.41,-1.57,-1.47,5.74,0.00,-0.19

In [11]:
x_dev = tf.cast(df_dev[CS230.data.COLUMNS_HUMAN_INPUT].values, tf.float32)
y_dev = tf.cast(df_dev[CS230.data.COLUMNS_DERIV].values, tf.float32)

In [12]:
df_dev[CS230.data.COLUMNS_HUMAN_INPUT].values

array([[ 13.5,   0.7, -32.9],
       [  0. ,  10.4, -35.6],
       [  0. ,   0.8, -33.1],
       ...,
       [  0. ,  89.9,   0.4],
       [  0. ,  11.4, -66.8],
       [ 18.1,   3.6,  -0.6]])

In [13]:
df_dev[CS230.data.COLUMNS_DERIV].values

array([[ 7.000e-02,  1.000e-02,  0.000e+00, ...,  7.000e-02,  1.000e-02,
        -5.200e-01],
       [-1.100e+00,  2.160e+00, -3.000e-02, ..., -1.110e+00, -2.100e-01,
         4.300e-01],
       [-7.000e-02,  1.000e-02,  0.000e+00, ...,  4.300e-01,  0.000e+00,
        -2.000e-01],
       ...,
       [ 4.890e+00,  4.410e+00,  2.000e-02, ..., -2.176e+01,  0.000e+00,
         0.000e+00],
       [-2.800e-01,  1.181e+01,  2.000e-02, ...,  2.780e+00, -2.600e-01,
         2.000e-02],
       [ 1.520e+00,  2.050e+00,  1.000e-02, ...,  1.030e+00,  4.000e-02,
         7.000e-02]])

# predict against dev set

In [14]:
prediction = model.predict(x_dev, steps=1)

In [15]:
prediction

array([[3.7413883e-01, 4.8117518e-01, 4.3494594e-01, ..., 4.0864593e-01,
        5.3942710e-01, 3.6216921e-01],
       [3.2615662e-04, 0.0000000e+00, 4.0998727e-01, ..., 9.9941278e-01,
        0.0000000e+00, 0.0000000e+00],
       [3.9627603e-01, 1.9214451e-03, 2.9007673e-02, ..., 1.5660104e-01,
        4.0881053e-01, 1.6304255e-03],
       ...,
       [1.1694133e-03, 2.4655461e-04, 3.0100346e-06, ..., 5.3614026e-01,
        1.0000000e+00, 7.4196130e-01],
       [4.2015645e-01, 4.0042001e-01, 1.7524204e-01, ..., 2.5595874e-01,
        8.3210087e-01, 2.5002569e-01],
       [2.9802322e-08, 0.0000000e+00, 1.0230130e-01, ..., 9.9998474e-01,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)