In [1]:
import copy
import matplotlib.pyplot as plt
import numpy
import pandas
import plotly
import six
import tensorflow as tf

import CS230

In [2]:
file_paths = CS230.data.get_all_file_paths()

# experiment 3 - largest possible network

In [3]:
file_path = file_paths[0]
data_columns = copy.deepcopy(CS230.data.COLUMNS_ALL)
data_columns.extend(CS230.data.COLUMNS_MOTION_DERIVS)
label_columns = copy.deepcopy(CS230.data.COLUMNS_MOTION_DERIVS)

train_percent = 0.9
dev_percent = 0.05
test_percent = 0.05

df = CS230.data.load(file_path)
df = CS230.data.stride_rows(df, stride=50)
df.dropna(axis=0, inplace=True)
df = CS230.data.add_derivatives(df, stride=1)
df = CS230.data.clean_discontinuities(df, stride=1)

#df = tf.keras.utils.normalize(df, axis=0)  # TODO details

df_train, df_dev, df_test, data_columns, label_columns = CS230.data.get_data_sets(df, 
                                                            train_percent, dev_percent, test_percent, 
                                                            data_columns, label_columns)

In [4]:
df_train.head()

,data_HDOP,data_PDOP,data_PPS,data_altitude,data_axCG,data_ayCG,data_azCG,data_brake,data_chassisAccelFL,data_chassisAccelFR,...,label_deriv_rollAngle,label_deriv_rollRate,label_deriv_vxCG,label_deriv_vyCG,label_deriv_wheelAccelFL,label_deriv_wheelAccelFR,label_deriv_wheelAccelRL,label_deriv_wheelAccelRR,label_deriv_yawAngle,label_deriv_yawRate
8910,1.1,1.7,5.0,197.819,0.16,-0.15,9.77,0.0,9.535,9.692,...,0.00,-0.08,0.00,0.00,0.10,0.29,0.10,0.14,0.00,-0.13
38560,0.7,1.2,5.0,202.958,-5.67,4.66,9.81,4.2,11.576,1.687,...,0.35,3.32,-0.27,0.01,-2.06,2.95,-20.80,-11.64,0.29,-2.04
20478,0.6,1.1,5.0,248.678,-1.52,7.40,9.09,0.0,7.102,10.565,...,0.10,5.52,-0.05,-0.02,-7.26,-7.45,-2.16,-6.24,1.40,-0.90
36791,0.7,1.2,5.0,194.129,-1.31,-9.35,8.55,0.0,8.829,11.291,...,-0.07,2.07,-0.12,0.10,10.89,2.46,-1.57,-1.86,-1.26,-2.74
13920,0.8,1.4,5.0,197.875,0.13,-0.14,9.77,0.0,9.535,9.624,...,0.01,-0.42,0.01,-0.01,-0.09,0.10,0.00,-0.18,-0.01,0.62

In [5]:
df_train[label_columns].head()

,label_deriv_axCG,label_deriv_ayCG,label_deriv_pitchAngle,label_deriv_pitchRate,label_deriv_rollAngle,label_deriv_rollRate,label_deriv_vxCG,label_deriv_vyCG,label_deriv_wheelAccelFL,label_deriv_wheelAccelFR,label_deriv_wheelAccelRL,label_deriv_wheelAccelRR,label_deriv_yawAngle,label_deriv_yawRate
8910,-0.03,0.01,0.00,0.41,0.00,-0.08,0.00,0.00,0.10,0.29,0.10,0.14,0.00,-0.13
38560,1.98,0.51,-0.14,-4.52,0.35,3.32,-0.27,0.01,-2.06,2.95,-20.80,-11.64,0.29,-2.04
20478,-0.05,-2.12,0.26,-0.76,0.10,5.52,-0.05,-0.02,-7.26,-7.45,-2.16,-6.24,1.40,-0.90
36791,-1.02,0.46,0.07,-3.37,-0.07,2.07,-0.12,0.10,10.89,2.46,-1.57,-1.86,-1.26,-2.74
13920,-0.02,0.01,0.00,0.25,0.01,-0.42,0.01,-0.01,-0.09,0.10,0.00,-0.18,-0.01,0.62

In [6]:
print('input size: %s' % len(data_columns))
print('output size: %s' % len(label_columns))
print('input+output size: %s' % len(df_train.columns))

input size: 70
output size: 14
input+output size: 84

In [7]:
model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(len(data_columns), activation='relu'))

model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(len(data_columns), activation='relu'))

#model.add(tf.keras.layers.Dropout(0.2))
#model.add(tf.keras.layers.Dense(len(data_columns), activation='relu'))

model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(len(label_columns), activation='sigmoid'))

In [8]:
optimizer = tf.train.AdamOptimizer(0.001)
#optimizer = tf.keras.optimizers.SGD(lr=0.03, decay=1e-6, momentum=0.9, nesterov=True)

model.compile(
    optimizer=optimizer, 
    loss='mean_squared_error', 
    metrics=['mean_absolute_error']
)

WARNING:tensorflow:From /home/dave/venv/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [9]:
x_train = tf.cast(df_train[data_columns].values, tf.float64)
y_train = tf.cast(df_train[label_columns].values, tf.float64)

In [10]:
history = model.fit(x_train, y_train, epochs=20, steps_per_epoch=200)

WARNING:tensorflow:From /home/dave/venv/py3.6/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/dave/venv/py3.6/lib/python3.6/site-packages/tensorflow/python/keras/utils/losses_utils.py:170: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/dave/venv/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/20
200/200 [==============================] - 11s 53ms/step - loss: 20.3100 - mean_absolute_error: 1.7001
Epoch 2/20
200/200 [==============================] - 10s 50ms/step - loss: 20.2706 - mean_absolute_error: 1.6770
Epoch 3/20
200/200 [==============================] - 10s 51ms/step - loss: 20.2703 - mean_absolute_error: 1.6768
Epoch 4/20
200/200 [==============================] - 10s 52ms/step - loss: 20.2701 - mean_absolute_error: 1.6767
Epoch 5/20
200/200 [==============================] - 10s 52ms/step - loss: 20.2700 - mean_absolute_error: 1.6767
Epoch 6/20
200/200 [==============================] - 10s 51ms/step - loss: 20.2700 - mean_absolute_error: 1.6767
Epoch 7/20
200/200 [==============================] - 10s 50ms/step - loss: 20.2700 - mean_absolute_error: 1.67671s - loss: 20.
Epoch 8/20
200/200 [==============================] - 10s 50ms/step - loss: 20.2700 - mean_absolute_error: 1.6767
Epoch 9/20
200/200 [==============================] - 10s 50ms/step - loss: 20.2700 - mean_absolute_error: 1.6766
Epoch 10/20
200/200 [==============================] - 10s 51ms/step - loss: 20.2700 - mean_absolute_error: 1.6766
Epoch 11/20
200/200 [==============================] - 10s 49ms/step - loss: 20.2700 - mean_absolute_error: 1.6766
Epoch 12/20
200/200 [==============================] - 10s 50ms/step - loss: 20.2700 - mean_absolute_error: 1.6766
Epoch 13/20
200/200 [==============================] - 10s 51ms/step - loss: 20.2700 - mean_absolute_error: 1.6766
Epoch 14/20
200/200 [==============================] - 10s 51ms/step - loss: 20.2700 - mean_absolute_error: 1.6766
Epoch 15/20
149/200 [=====================>........] - ETA: 2s - loss: 20.2700 - mean_absolute_error: 1.6766

KeyboardInterrupt:

In [ ]:
plt.plot(history.history['mean_absolute_error'])
#plt.plot(history.history['val_acc'])
plt.title('model error')
plt.ylabel('mean abs error')
plt.xlabel('epoch')

In [ ]:
x_dev = tf.cast(df_dev[data_columns].values, tf.float32)
y_dev = tf.cast(df_dev[label_columns].values, tf.float32)

In [ ]:
dev_predictions = model.predict(x_dev, steps=1)

In [ ]:
df_dev_predictions = pandas.DataFrame(dev_predictions, columns=label_columns)

In [ ]:
df_dev[data_columns].head()

In [ ]:
df_dev[label_columns].head()

In [ ]:
df_dev_predictions.head()

In [ ]:
error = df_dev.reset_index(drop=True)[label_columns] - df_dev_predictions[label_columns]

In [ ]:
error.head()