In [1]:
import numpy
import os
import pandas
import plotly
import pyarrow
import pyarrow.parquet as pq
import sys

plotly.offline.init_notebook_mode(connected=True)

In [15]:
DATA_DIR = '2014_Targa_Sixty-Six'

In [16]:
FILE_NAMES = [x for x in os.listdir(DATA_DIR) if x.endswith('.parquet')]
FILE_NAMES.sort()
print(FILE_NAMES)

['20140221_01_01_03_250lm.parquet', '20140221_01_02_03_250lm.parquet', '20140221_02_01_03_250lm.parquet', '20140221_03_01_03_250lm.parquet', '20140221_03_02_03_250lm.parquet', '20140221_03_03_03_250lm.parquet', '20140221_04_01_03_250lm.parquet', '20140222_01_01_03_250lm.parquet', '20140222_02_01_03_250lm.parquet', '250lm.parquet']

In [35]:
file_path = os.path.join(DATA_DIR, FILE_NAMES[0])

In [36]:
table = pq.read_table(file_path)

In [37]:
df = table.to_pandas()

In [38]:
sorted(list(df.columns), key=lambda s: s.lower())

['altitude',
 'axCG',
 'ayCG',
 'azCG',
 'brake',
 'chassisAccelFL',
 'chassisAccelFR',
 'chassisAccelRL',
 'chassisAccelRR',
 'clutch',
 'deflectionFL',
 'deflectionFR',
 'deflectionRL',
 'deflectionRR',
 'distance',
 'engineSpeed',
 'gpsOrientMode',
 'gpsPosMode',
 'gpsTime',
 'gpsVelMode',
 'handwheelAngle',
 'HDOP',
 'horizontalSpeed',
 'latitude',
 'longitude',
 'numSVsTracked',
 'orientAccuracy_heading',
 'orientAccuracy_pitch',
 'orientAccuracy_roll',
 'PDOP',
 'pitchAngle',
 'pitchRate',
 'posAccuracy_down',
 'posAccuracy_east',
 'posAccuracy_north',
 'PPS',
 'rollAngle',
 'rollRate',
 'sideSlip',
 'throttle',
 'time',
 'vEast',
 'velAccuracy_down',
 'velAccuracy_east',
 'velAccuracy_north',
 'vNorth',
 'vUp',
 'vxCG',
 'vyCG',
 'vzCG',
 'wheelAccelFL',
 'wheelAccelFR',
 'wheelAccelRL',
 'wheelAccelRR',
 'yawAngle',
 'yawRate']

In [39]:
df.head()

,time,handwheelAngle,throttle,brake,clutch,engineSpeed,PPS,gpsTime,latitude,longitude,...,chassisAccelRL,chassisAccelRR,deflectionFL,deflectionFR,deflectionRL,deflectionRR,wheelAccelFL,wheelAccelFR,wheelAccelRL,wheelAccelRR
0,0.000,1.4,3.3,0.0,95.0,1662,4.97,52158.5,NaN,NaN,...,8.633,9.231,-0.0,-0.001,0.003,0.0,10.01,10.40,9.12,9.32
1,0.001,1.4,3.3,0.0,95.0,1662,4.95,52158.5,NaN,NaN,...,9.182,10.114,-0.0,-0.001,0.003,0.0,9.91,10.30,8.44,9.12
2,0.002,1.4,3.3,0.0,94.5,1662,4.96,52158.5,NaN,NaN,...,8.731,9.064,-0.0,-0.001,0.003,0.0,9.61,10.20,7.75,9.03
3,0.003,1.4,3.3,0.0,94.5,1662,4.97,52158.5,NaN,NaN,...,9.280,8.868,-0.0,-0.001,0.003,0.0,9.61,10.10,7.46,9.42
4,0.004,1.4,3.3,0.0,94.0,1662,4.97,52158.5,NaN,NaN,...,8.662,8.986,-0.0,-0.001,0.003,0.0,10.01,10.01,9.42,10.99

In [40]:
sig_names = ['time', 'handwheelAngle', 'throttle', 'brake', 'latitude', 'longitude', 'altitude', 'horizontalSpeed', 'vxCG', 'vyCG', 'yawAngle', 'pitchAngle', 'rollAngle', 'distance']

In [41]:
df[['time', 'handwheelAngle', 'throttle', 'brake', 'latitude', 'longitude', 'altitude', 'horizontalSpeed', 'vxCG', 'vyCG', 'yawAngle', 'pitchAngle', 'rollAngle', 'distance']].head()

,time,handwheelAngle,throttle,brake,latitude,longitude,altitude,horizontalSpeed,vxCG,vyCG,yawAngle,pitchAngle,rollAngle,distance
0,0.000,1.4,3.3,0.0,NaN,NaN,NaN,0.0,0.0,0.0,1.9,-0.9,0.0,0.0
1,0.001,1.4,3.3,0.0,NaN,NaN,NaN,0.0,0.0,0.0,1.9,-0.9,0.0,0.0
2,0.002,1.4,3.3,0.0,NaN,NaN,NaN,0.0,0.0,0.0,1.9,-0.9,0.0,0.0
3,0.003,1.4,3.3,0.0,NaN,NaN,NaN,0.0,0.0,0.0,1.9,-0.9,0.0,0.0
4,0.004,1.4,3.3,0.0,NaN,NaN,NaN,0.0,0.0,0.0,1.9,-0.9,0.0,0.0

In [42]:
len(df)

535468

In [43]:
data = []

time = df['time'].values

length = 1000

for sig_name in sig_names[1:]:
    trace = plotly.graph_objs.Scatter(
        x = time[:length],
        y = df[sig_name].values[:length],
        name = sig_name
    )
    data.append(trace)

plotly.offline.iplot(data)